/*
 * This module hooks into the newOrder to add the customers
 * @author	 GetResponse
 * @copyright  GetResponse
 * @license	http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

(function(name,buider){if(APP&&APP.core){APP.core.define(name,buider);return;}
throw new Error('Nie ma APP.core.define');}('triggerAddToCycle',function(box){var $=box.dom||jQuery,win=window,doc=win.document,autoresponder,templateBuilder=box.templateBuilder.getInstance({block:'<div class="control-group triggerAddToCycleContainer">'
+'<label class="{{labelClassName}}">'
+'<input class="add-to-cycle-checkbox" type="checkbox" name="{{activatorName}}" id="add_to_cycle" value="yes" data-define="activator"/>'
+'{{translateDontAddToTheCycleOnDay}}'
+'</label>'
+'<div class="controls"><select name="{{dayName}}" data-define="day" disabled="disabled"></select></div>'
+'<img src="/modules/getresponse/img/{{loaderFileName}}" data-define="loader" style="display: none;" {{loaderAdditionalParams}}/>'
+'</div>',option:'<span><strong>{{translateDay}} {{number}}:</strong> {{count}} {{translateMessages}}</span>',message:'<em title="{{message}}">{{message}}</em>'});function plural(translatedString,number){number=number||0;return translatedString.replace(/\{(.+?\|.+?)\}/,function(all,match){match=match.split('|',number+2);if(undefined===match[number]){return match.pop();}
return match[number];});}
autoresponder={url:'',STORAGE:'autoresponderData',activation:false,day:undefined,addEmptyDay:false,forceDay:undefined,campaign:undefined,translations:{},$container:undefined,template:undefined,select:undefined,names:{activatorName:'add_to_cycle',dayName:'cycle_day'},variables:{labelClassName:'control-label',loaderAdditionalParams:'',loaderFileName:'loader.white.gif'},build:function(){var storageData,template;storageData=this.getDataFromStorage();this.activation=storageData.activation;this.day=storageData.day;this.addEmptyDay=!this.STORAGE;template=templateBuilder.build('block',$.extend({},this.translations,this.names,this.variables));this.template=template;this.$container.html('');template.insert(this.$container[0]);this.attachEvents();},attachEvents:function(){var template=this.template,that=this;template.activator.checked=this.activation;$(template.activator).bind({click:function(){that.setActivation(this.checked);}}).triggerHandler('click');$(template.day).fullSelectLc({mode:false,className:'daySelectAutoresponder',onBuild:function(){that.select=this;if(this.select.disabled){$(this.template.container).addClass('disabled');}},afterClickItem:function(e,fSelect){that.day=fSelect.elements.selected[0].dataItem.dayNumber;that.addEmptyDay=false;that.saveDataInStorage();}});this.setCampaign(this.campaign,false);},buildOptionsFragment:function(data){var fragment=doc.createDocumentFragment(),option,i,ln,item,text;for(i=0,ln=data.length;i<ln;i+=1){item=data[i];if(undefined===item){continue;}
text=this.translations.translateDay+' '+i+': '+item.length+' '+plural(this.translations.translateMessages,item.length);option=new win.Option(text,i);option.innerHTML=text;option.messages=item;option.dayNumber=i;fragment.appendChild(option);}
return fragment;},setActivation:function(activation){var template=this.template;activation=!!activation;this.activation=activation;template.day.disabled=!activation;if(this.select){$(this.select.template.container).toggleClass('disabled',!activation);}
this.saveDataInStorage();},setDay:function(day){this.day=day;this.addEmptyDay=true;},setCampaign:function(campaign,clearDay){var that=this,template=this.template;if(this.campaign===campaign){clearDay=false;}
this.campaign=campaign;if(!template){return;}
if(clearDay){this.day=undefined;this.addEmptyDay=false;}
template.loader.style.cssText='';$.post(this.url,{campaign_id:this.campaign,campaign_name:'todo',api_key:this.api_key,api_url:this.api_url},function(data){var options=that.buildOptionsFragment(that.prepareData(data.table||[]));while(template.day.options.length){template.day.remove(0);}
template.loader.style.cssText='display: none;';if(!options.hasChildNodes()||that.template!==template){template.remove();return;}
if(template.wrapper&&!template.wrapper.parentNode){template.insert(that.$container[0]);}
template.day.appendChild(options);$(template.day).val(that.day);that.day=$(template.day).val();if(null===that.day){$(template.day).val(template.day.options[0].dayNumber);that.day=$(template.day).val();}
$(template.day).trigger('rebuildList').trigger('rebuildValue');that.rebuildSelectList();that.saveDataInStorage();},'json');},saveDataInStorage:function(){var save={activation:this.activation,day:this.day};if(!this.STORAGE){return;}
try{win.localStorage.setItem(this.STORAGE,JSON.stringify(save));}catch(e){}},getDataFromStorage:function(){var defaultValues={activation:this.activation,day:this.day};if(!this.STORAGE){return defaultValues;}
try{return JSON.parse(win.localStorage.getItem(this.STORAGE))||defaultValues;}catch(e){return defaultValues;}},prepareData:function(data){var i,ln,newData=[],el;if(data[0]){for(i=0,ln=data.length;i<ln;i+=1){el=data[i];if(!newData[el.on_day]){newData[el.on_day]=[];}
newData[el.on_day].push(el.messages_subject);}}
if(undefined!==this.forceDay&&!newData[this.forceDay]){newData[this.forceDay]=[];}
if(undefined!==this.day&&!newData[this.day]&&this.addEmptyDay){newData[this.day]=[];}
return newData;},rebuildSelectList:function(){var select=this.select,elements=select.elements.elements,item,messages,translations,i,ln,j,mLn,to;for(i=0,ln=elements.length;i<ln;i+=1){item=elements[i];item.label.style.display='none';messages=item.dataItem.messages;translations=$.extend({number:String(item.dataItem.dayNumber),count:String(messages.length)},this.translations);translations.translateMessages=plural(translations.translateMessages,messages.length);templateBuilder.build('option',translations).insert(item.container);mLn=messages.length;if(0===mLn){templateBuilder.build('message',{message:this.translations.translateNoMessages}).insert(item.container);continue;}
to=mLn<4?mLn:2;for(j=0,mLn=messages.length;j<to;j+=1){templateBuilder.build('message',{message:messages[j]}).insert(item.container);}
if(to<mLn){templateBuilder.build('message',{message:'+'+(mLn-to)+' '+this.translations.translateMore}).insert(item.container);}}}};return{init:function(){box.subscribe('triggerAddToCycle.build',function(){autoresponder.build();});box.subscribe('triggerAddToCycle.setConfig',function(config){autoresponder.url=config.url;autoresponder.api_key=config.api_key;autoresponder.api_url=config.api_url;autoresponder.translations=config.translations;$.extend(autoresponder.variables,config.variables);autoresponder.$container=$(config.container);autoresponder.forceDay=config.forceDay;if(config.storageName||false===config.storageName){autoresponder.STORAGE=config.storageName;}
if(config.names){if(config.names.activator){autoresponder.names.activatorName=config.names.activator;}
if(config.names.day){autoresponder.names.dayName=config.names.day;}}});box.subscribe('triggerAddToCycle.setCampaign',function(campaign){autoresponder.setCampaign(campaign,true);});box.subscribe('triggerAddToCycle.setDay',function(day){autoresponder.setDay(day);});box.subscribe('triggerAddToCycle.getDay',function(){return autoresponder.day;});box.subscribe('triggerAddToCycle.setActivation',function(activation){var template=autoresponder.template;activation=!!activation;if(activation!==autoresponder.activation){template.activator.checked=activation;$(template.activator).triggerHandler('click');}});box.subscribe('triggerAddToCycle.getActivation',function(){return autoresponder.activation?'yes':'no';});box.subscribe('triggerAddToCycle.destroy',function(){var template=autoresponder.template;if(template){if(template.wrapper.parentNode){template.remove();}
template.wrapper=undefined;}
autoresponder.url='';autoresponder.STORAGE='autoresponderData';autoresponder.activation=false;autoresponder.addEmptyDay=false;autoresponder.day=undefined;autoresponder.forceDay=undefined;autoresponder.campaign=undefined;autoresponder.translations={};autoresponder.$container=undefined;autoresponder.template=undefined;autoresponder.select=undefined;autoresponder.names={activatorName:'add_to_cycle',dayName:'onday'};});}};}));$(function(){APP.require(APP.files.js.templateBuilder,function(){APP.core.start('triggerAddToCycle');});});