/*
 * This module hooks into the newOrder to add the customers
 * @author	 GetResponse
 * @copyright  GetResponse
 * @license	http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

(function($){var selectBuilder=function(){var defaultOptions={onFocusInput:undefined,onOpen:undefined,onBlurInput:undefined,onClose:undefined,onAfterLoad:undefined,onBuild:undefined,onClickLi:undefined,clickItem:undefined,onClickLiAfter:undefined,afterClickItem:undefined,onShowClose:undefined,onAfterClose:undefined,onHoverLi:undefined,onItemHover:undefined,multiselect:false,multiselectNoResults:'No results selected',multiselectAllResults:'All results selected',addCheckAll:undefined,attrArr:false,className:'',name:'defaultName',moreLink:false,secondMoreLink:false,customLinkMask:false,insertValueToArrayName:false,setListSize:'toParentWidth',separator:false,mode:true,valueDecorator:undefined,selectionRange:false,search:false,searchPlaceholder:'Quick search',searchLimit:9},doc=window.document,create=Object.create||function(proto){function F(){}
F.prototype=proto;F.prototype.constructor=F;return new F();},style=(function(){var head=doc.getElementsByTagName('head')[0],css=doc.createElement('style'),sheet;css.type='text/css';head.appendChild(css);sheet=css.sheet||css.styleSheet;return{addRules:function(rules){var k;for(k in rules){if(rules.hasOwnProperty(k)){if(sheet.insertRule){sheet.insertRule(k+' {'+rules[k]+'}',0);}else if(sheet.addRule){sheet.addRule(k,rules[k],0);}}}}};}()),templateBuilder=APP().templateBuilder.getInstance({container:'<div class="FullSelectLcContainer FullSelectLcContainerDefault close" data-define="container">'
+'<input class="FullSelectLcInput inputLc" type="text" readonly="readonly" data-define="input"/>'
+'<input type="button" class="FullSelectLcButton buttonLc" value="&#x25BC;" data-define="button"/>'
+'<div class="FullSelectLcContainerList" data-define="listContainer">'
+'<div class="FullSelectLcCustomElem1 custom1Lc" data-define="firstElement"></div>'
+'<div class="FullSelectLcSearch deactivate" data-define="search" data-event-click="search"><input type="text" placeholder="{{placeholder}}" data-define="searchInput"/><span data-icon="k"></span></div>'
+'<ul class="list" data-define="list" data-define="list"></ul>'
+'<ul class="more" data-define="moreList"></ul>'
+'<ul class="more second" data-define="secondMoreList"></ul>'
+'</div>'
+'</div>',lipatern:{one:'<li>'
+'<input type="radio" data-input="radio"/>'
+'<span data-content="label"></span>'
+'</li>',multi:'<li>'
+'<input type="checkbox" data-input="checkbox"/>'
+'<span data-content="label"></span>'
+'</li>'},moreListLipatern:'<li><span data-content="label"></span></li>'}),elementsProto={elements:[],selected:[],lastActionsElement:undefined,length:0,visible:false,selectAllElement:undefined,getInstance:function(){var instance=create(this);instance.elements=[];instance.selected=[];instance.length=0;return instance;},getVisibleInstance:function(){var instance=this.getInstance(),elements=this.elements,el,ln=this.length,i;instance.visible=true;for(i=0;i<ln;i+=1){el=elements[i];if(el.visible){instance.push(el);if(el.selected){instance.select(el.container,false);}}}
if(this.lastActionsElement&&this.lastActionsElement.visible){instance.lastActionsElement=this.lastActionsElement;}else{instance.lastActionsElement=instance.elements[0];}
return instance;},push:function(element){var length;length=this.elements.push(element);this.length=length;if(!this.visible){element.container.positionInElementsArray=length-1;}
return length;},getPosition:function(container){var i,ln=this.length;if(undefined===container.positionInElementsArray||this.visible){for(i=0;i<ln;i+=1){if(this.elements[i].container===container){return i;}}}else{return container.positionInElementsArray;}},select:function(container,sort){var element=this.elements[this.getPosition(container)],that=this;this.selected.push(element);sort=undefined===sort?true:sort;if(sort){this.selected.sort(function(elementA,elementB){return that.getPosition(elementA.container)-that.getPosition(elementB.container);});}
this.lastActionsElement=element;this.onSelect(element);element.selected=true;},unselect:function(container){var element=this.elements[this.getPosition(container)],index;if(element&&element.selected){index=this.selected.indexOf(element);if(-1!==index){this.selected.splice(index,1);this.onUnselect(element);element.selected=false;this.lastActionsElement=element;}}},selectAll:function(){var i,ln=this.elements.length,element;for(i=0;i<ln;i+=1){element=this.elements[i];if(element!==this.selectAllElement&&!element.selected){this.onSelect(element);element.selected=true;}}
this.selected=this.elements.slice();if(this.selectAllElement){if(this.selectAllElement===this.selected[0]){this.selected.shift();}else if(-1!==this.selected.indexOf(this.selectAllElement)){this.selected.splice(this.selected.indexOf(this.selectAllElement),1);}}
this.lastActionsElement=this.selectAllElement;},unselectAll:function(){var i,ln=this.selected.length,element;for(i=0;i<ln;i+=1){element=this.selected[i];if(element!==this.selectAllElement&&element.selected){this.onUnselect(element);element.selected=false;}}
this.selected.length=0;this.lastActionsElement=this.selectAllElement;},toggle:function(container){var element=this.elements[this.getPosition(container)];if(element.selected){this.unselect(container);}else{this.select(container);}},visibilityToggle:function(regexp){var elements=this.elements,i,ln=elements.length,el,test;for(i=0;i<ln;i+=1){el=elements[i];test=regexp.test(el.label.innerText||el.label.textContent||'')||regexp.test(el.container.title||'');this[test?'show':'hide'](el.container);}},show:function(container){var element=this.elements[this.getPosition(container)];element.visible=true;$(container).removeClass('searchHide');},hide:function(container){var element=this.elements[this.getPosition(container)];element.visible=false;$(container).addClass('searchHide');},onSelect:function(element){$(element.container).addClass('selected');element.input.checked=true;element.dataItem.selected=true;},onUnselect:function(element){$(element.container).removeClass('selected');element.input.checked=false;element.dataItem.selected=false;},onSelectAll:function(){var element=this.selectAllElement.container;$(element).addClass('all');element.querySelector('input').checked=true;},onUnselectAll:function(){var element=this.selectAllElement.container,$element=$(element);if($element.hasClass('all')){$(element).removeClass('all');element.querySelector('input').checked=false;}},getSelectedValues:function(decorator){var values=[],selected=this.selected,i,ln=selected.length,label,labelText;for(i=0;i<ln;i+=1){label=selected[i].label;labelText=label.textContent||label.innerText;if(labelText){values[values.length]=labelText;}}
if('function'===typeof decorator){return decorator.call(values,this.elements);}
return values.join('; ');}},selectProto={options:{},select:undefined,template:undefined,opened:false,bodyCloseEventHandler:undefined,bodyKeyUpEventHandler:undefined,bodyKeyPressEventHandler:undefined,bodyKeyDownEventHandler:undefined,elements:undefined,init:function(select,options){this.options=$.extend({},defaultOptions,options);options=this.options;if(/\{count:numeric\}/.test(options.multiselect)){options.multiselect='{element:0}'+options.multiselect.replace(/\{count:numeric\}/,'{count:-1}');}
this.select=select;this.elements=elementsProto.getInstance();if(!options.valueDecorator){if(options.multiselect&&'string'===typeof options.multiselect){options.valueDecorator=function(elements){var that=this,ln=this.length;if(!ln){return options.multiselectNoResults;}
if(ln===elements.length-(options.addCheckAll?1:0)){return options.multiselectAllResults;}
if(ln>1){return options.multiselect.replace(/\{(.*?):(.*?)\}/g,function(all,name,value){switch(name){case'element':value=Number(value)||0;return that[value]||'';case'count':value=Number(value);return ln+value;case'plural':value=value.split('|');if(ln>2){return value[1]||value[0]||'';}
return value[0]||'';}});}
return this[0]||'';};}}
this.build();},build:function(){var that=this,options=this.options;this.template=templateBuilder.build({name:'container',variables:{placeholder:options.searchPlaceholder},decorator:function(template){var data=that.select.options||{length:0},lipatern=templateBuilder.build('lipatern.'+(options.multiselect?'multi':'one')),moreList=template.moreList,secondMoreList=template.secondMoreList;template.list.appendChild(that.buildList(data,lipatern.wrapper));if(options.moreLink&&options.moreLink instanceof Array){lipatern=templateBuilder.build('moreListLipatern');moreList.appendChild(that.buildMoreList(options.moreLink,lipatern.wrapper));if(data.length<2){moreList.className+=' lessThan2Items';}}else{moreList.parentNode.removeChild(moreList);}
if(options.secondMoreLink&&options.secondMoreLink instanceof Array){lipatern=templateBuilder.build('moreListLipatern');secondMoreList.appendChild(that.buildMoreList(options.secondMoreLink,lipatern.wrapper));if(data.length<2){secondMoreList.className+=' lessThan2Items';}}else{secondMoreList.parentNode.removeChild(secondMoreList);}
template.button.tabIndex=-1;template.input.value=that.elements.getSelectedValues(options.valueDecorator);if(options.className){$(template.container).addClass(options.className);}
options.search=options.search&&data.length>options.searchLimit;if(options.search){$(template.search).removeClass('deactivate');}else{$(template.search).detach();}
return template;}});switch(options.setListSize){case'toParentWidth':break;default:this.template.listContainer.style.width='number'===typeof options.setListSize?options.setListSize+'px':options.setListSize;break;}
this.attachEvents();if(this.select.tabIndex){this.template.input.tabIndex=this.select.tabIndex;}
this.select.tabIndex=-1;if(this.select.name){options.name=this.select.name;}
this.select.removeAttribute('name');this.template.insert(this.select,'beforeBegin');$(this.select).addClass('fullSelectHide').appendTo(this.template.container);if(options.onAfterLoad){options.onAfterLoad($(this.select),this.getTable());}
if(options.onBuild){options.onBuild.call(this);}},rebuildList:function(){var template=this.template,lipatern=templateBuilder.build('lipatern.'+(this.options.multiselect?'multi':'one'));this.elements.elements=[];this.elements.selected=[];this.elements.length=0;template.list.innerHTML='';template.list.appendChild(this.buildList(this.select.options||{length:0},lipatern.wrapper));},buildList:function(data,patern){var fragment=doc.createDocumentFragment(),item,label,input,options=this.options,attrArr=options.attrArr||false,name=this.select.name||options.name,itemData,itemName,itemValue,li,i,ln,j,attrArrLn=attrArr.length,attrItem,linkMask;if(options.addCheckAll){li=patern.cloneNode(true);$(li).addClass('checkAll');li.setAttribute('data-event-click','checkAll');label=li.querySelector('[data-content="label"]');label.innerHTML=options.addCheckAll;label.removeAttribute('data-content');input=li.querySelector('[data-input]');input.name='';input.value='';input.tabIndex=-1;this.elements.push({container:li,input:input,label:label,visible:true});this.elements.selectAllElement=this.elements.elements[this.elements.length-1];fragment.appendChild(li);}
for(i=0,ln=data.length;i<ln;i+=1){linkMask=options.customLinkMask;item=data[i];itemName=name;li=patern.cloneNode(true);if(options.separator===i){$(li).addClass('separator');}
itemData={title:item.title||'',value:item.value||'',innerHTML:item.innerHTML};li.setAttribute('data-event-click','li');li.setAttribute('data-event-hover','li');input=li.querySelector('[data-input]');label=li.querySelector('[data-content="label"]');if(attrArr){for(j=0;j<attrArrLn;j+=1){attrItem=attrArr[j];if(item.hasAttribute('data-'+attrItem)){itemData['name'===attrItem?'innerHTML':attrItem]=item.getAttribute('data-'+attrItem);}
if(undefined!==itemData['name'===attrItem?'innerHTML':attrItem]){input.setAttribute('data-'+attrItem,itemData['name'===attrItem?'innerHTML':attrItem]);}}}
itemValue=itemData.value;input.value=itemValue;if(!/\[\]$/.test(itemName)&&(options.mode||options.multiselect)){itemName+='[]';}
if(options.insertValueToArrayName){itemName=itemName.replace(/(\[\]$|$)/,'['+itemValue+']');}
input.name=itemName;input.tabIndex=-1;label.innerHTML=itemData.innerHTML;if(linkMask){if('string'===typeof linkMask){linkMask=linkMask.replace(/\[\[(.*?)\]\]/g,function(match,matchWord){var param=matchWord;switch(matchWord){case'val':param='value';break;case'name':param='innerHTML';break;}
if(undefined!==itemData[param]){return itemData[param];}
if(undefined!==item[param]){return item[param];}
return'[['+matchWord+']]';});}
linkMask=$(linkMask)[0];linkMask.tabIndex=-1;linkMask.setAttribute('data-event-click','linkMask');li.appendChild(linkMask);}
if(itemData.title){li.title=itemData.title;}
this.elements.push({dataItem:item,container:li,input:input,label:label,visible:true});if(item.selected){input.checked=true;this.elements.select(li,false);}
label.removeAttribute('data-content');input.removeAttribute('data-input');fragment.appendChild(li);}
if(this.elements.selectAllElement){if(this.elements.selected.length===this.elements.elements.length-1){this.elements.onSelectAll();}}
return fragment;},buildMoreList:function(data,patern){var fragment=doc.createDocumentFragment(),i,ln=data.length,clone,label;for(i=0;i<ln;i+=1){clone=patern.cloneNode(true);label=clone.querySelector('[data-content="label"]');label.innerHTML=data[i];label.removeAttribute('data-content');fragment.appendChild(clone);}
return fragment;},attachEvents:function(){var that=this,template=this.template,$container=$(template.container),triggerfocus=true;this.opened=!$container.hasClass('close');$container.bind({click:function(event,additionalOptions){var eventName;if(that.select.disabled){return;}
eventName=that.searchEventName('click',event.target);if(eventName){switch(eventName.name){case'search':break;case'li':return that.itemClickHandler(event,eventName.target,additionalOptions);case'linkMask':return that.linkMaskClickHandler(event,eventName.target,additionalOptions);case'checkAll':return that.checkAllClickHandler(event,eventName.target,additionalOptions);}}else if(that.opened){that.close();}else{that.open();}
event.stopPropagation();},hover:function(event){var eventName=that.searchEventName('hover',event.target);if(eventName){switch(eventName.name){case'li':return that.itemHoverHandler(event,event.target);}}}});$(template.input).bind({mousedown:function(){triggerfocus=false;},click:function(){triggerfocus=true;},focus:function(event,optionalData){optionalData=optionalData||{};if(optionalData.withoutHandler){return;}
if(triggerfocus){that.open();}}});$(this.select).bind({selectionChange:function(){var options=this.options,i,ln,elements=that.elements.elements,el;if(this.options.multiselect){for(i=0,ln=options.length;i<ln;i+=1){el=elements[i];if(el&&options[i].selected!==el.input.checked){$(el.container).trigger('click');}}}else{el=elements[this.selectedIndex];if(el&&!el.input.checked){$(el.container).trigger('click');}}},rebuildValue:function(){that.template.input.value=that.elements.getSelectedValues(that.options.valueDecorator);},rebuildList:function(){that.rebuildList();},close:function(e,force){if(force){that.opened=true;}
that.close();}});},searchEventName:function(type,target){var container=this.template.container,attribute='data-event-'+type;while(true){if(!target){return;}
if(target.hasAttribute(attribute)){return{target:target,name:target.getAttribute(attribute)};}
if(target===container){return;}
target=target.parentNode;}},checkAllClickHandler:function(event,target){var $target=$(target),options=this.options;if(!$target.hasClass('disabled')){if(options.onClickLi){options.onClickLi($(target),$(this.select),this.getTable());return false;}
if(options.clickItem){return options.clickItem.call(target,event,this);}
if($target.hasClass('all')){this.elements.unselectAll();this.elements.onUnselectAll();}else{this.elements.selectAll();this.elements.onSelectAll();}
if(options.onClickLiAfter){options.onClickLiAfter(target,$(this.select),this.getTable());}
if(options.afterClickItem){options.afterClickItem.call(target,event,this);}
this.template.input.value=this.elements.getSelectedValues(options.valueDecorator);}
event.stopPropagation();},itemClickHandler:function(event,target,additionalOptions){var $target=$(target),options=this.options,elements=this.elements,lastElement,lastElementNr,selected,selectedNr,i,ln,startNr,endNr,el;additionalOptions=additionalOptions||{};if($target.hasClass('off')){event.preventDefault();return false;}
if(options.onClickLi){options.onClickLi($(target),$(this.select),this.getTable());return false;}
if(options.clickItem){return options.clickItem.call(target,event,this,additionalOptions);}
lastElement=elements.lastActionsElement;if(lastElement){$(lastElement.container).removeClass('hover');}
if(!options.multiselect){elements.unselectAll();}
if(options.selectionRange&&options.multiselect){lastElementNr=elements.getPosition(target);lastElement=elements.elements[lastElementNr];if(lastElement.selected){elements.unselectAll();elements.select(target);}else{selected=elements.selected[0]||elements.elements[elements.selectAllElement?1:0]||{};if(selected.container){selectedNr=elements.getPosition(selected.container);if(lastElementNr<selectedNr){selected=elements.selected[elements.selected.length-1];selectedNr=elements.getPosition(selected.container);}
startNr=Math.min(lastElementNr,selectedNr);endNr=Math.max(lastElementNr,selectedNr);ln=elements.elements.length;for(i=elements.selectAllElement?1:0;i<ln;i+=1){el=elements.elements[i];if(i<startNr||i>endNr){if(el.selected){elements.unselect(el.container);}}else{if(!el.selected){elements.select(el.container);}}}}}
elements.lastActionsElement=lastElement;}else{elements.toggle(target);}
$(this.select).trigger('change');this.template.input.value=elements.getSelectedValues(options.valueDecorator);if(options.onClickLiAfter){options.onClickLiAfter(target,$(this.select),this.getTable());}
if(options.afterClickItem){options.afterClickItem.call(target,event,this,additionalOptions);}
if(elements.selectAllElement){if(elements.selected.length===elements.elements.length-1){elements.onSelectAll();}else{elements.onUnselectAll();}}
if(!options.multiselect&&!additionalOptions.stopPropagation){this.close();}
event.stopPropagation();},linkMaskClickHandler:function(event,targer){},itemHoverHandler:function(event,target){var options=this.options;if(options.onHoverLi){options.onHoverLi($(target),$(this.select),this.getTable());}
if(options.onItemHover){options.onItemHover.call(target,event,this);}},open:function(){var that=this,$body,options=this.options,search=options.search;if(this.opened){return;}
if(options.onShowClose){options.onShowClose($(this.template.input));}
if(options.onFocusInput){options.onFocusInput($(this.template.input),$(this.select),0);}
if(options.onOpen){options.onOpen.call(this);}
$body=$('body');$(this.template.container).removeClass('close').addClass('open');if(search){this.template.searchInput.focus();}
this.bodyCloseEventHandler=this.bodyCloseEventHandler||function(){that.close();};this.bodyKeyDownEventHandler=this.bodyKeyDownEventHandler||function(event){that.keyDownHandler(event,search&&event.target===that.template.searchInput);};this.bodyKeyPressEventHandler=this.bodyKeyPressEventHandler||function(event){that.keyPressHandler(event,search&&event.target===that.template.searchInput);};this.bodyKeyUpEventHandler=this.bodyKeyUpEventHandler||function(event){that.keyUpHandler(event,search&&event.target===that.template.searchInput);};$body.trigger('click.selectClose').unbind('click.selectClose',this.bodyCloseEventHandler).unbind('keydown',this.bodyKeyDownEventHandler).unbind('keypress',this.bodyKeyPressEventHandler).unbind('keyup',this.bodyKeyUpEventHandler).bind({'click.selectClose':this.bodyCloseEventHandler,keydown:this.bodyKeyDownEventHandler,keypress:this.bodyKeyPressEventHandler,keyup:this.bodyKeyUpEventHandler});this.opened=true;},close:function(){var options=this.options;if(!this.opened){return;}
$(this.template.container).removeClass('open').addClass('close');if(this.bodyCloseEventHandler){$('body').unbind('click.selectClose',this.bodyCloseEventHandler).unbind('keydown',this.bodyKeyDownEventHandler).unbind('keypress',this.bodyKeyPressEventHandler).unbind('keyup',this.bodyKeyUpEventHandler);}
if(options.search){this.template.searchInput.value='';}
this.opened=false;if(options.onBlurInput){options.onBlurInput($(this.template.input),$(this.select),0);}
if(options.onClose){options.onClose.call(this);}
if(options.onAfterClose){options.onAfterClose($(this.template.input));}
if(options.search){this.reduceList('');}},reduceList:function(text){var regexp,elements=this.elements;text=text.replace(/([\\\^\$\*\+\?\.\{\}\[\]\(\)])/g,"\\$1");try{regexp=new RegExp(text,'i');}catch(e){return;}
elements.visibilityToggle(regexp);},keyUpHandler:function(event,search){var keyCode=event.charCode||event.which||event.keyCode;switch(keyCode){case 9:case 40:case 38:case 13:case 27:break;case 32:default:if(search){this.reduceList(this.template.searchInput.value);}
break;}},keyPressHandler:function(event,search){var that=this,options=this.options,elements=this.elements,lastElement,i,ln=elements.length,keyCode=event.charCode||event.which||event.keyCode,regexp;switch(keyCode){case 9:case 40:case 38:case 13:case 27:break;case 32:if(search){break;}
break;default:if(search){break;}
clearTimeout(this.searchTextTimer);this.searchTextTimer=setTimeout(function(){that.searchText='';},1000);this.searchText=(this.searchText||'')+String.fromCharCode(event.keyCode).toLowerCase();event.preventDefault();try{regexp=new RegExp('^'+this.searchText,'i');}catch(e){break;}
lastElement=elements.lastActionsElement||elements.elements[0]||{};if(lastElement.container){for(i=0;i<ln;i+=1){if(regexp.test(elements.elements[i].label.innerHTML)){if(options.multiselect){$(lastElement.container).removeClass('hover');lastElement=elements.elements[i];$(lastElement.container).addClass('hover');elements.lastActionsElement=lastElement;}else{lastElement=elements.elements[i];$(lastElement.container).trigger('click',{stopPropagation:true});}
this.scrollToElement(lastElement);break;}}}
break;}},keyDownHandler:function(event,search){var keyCode=event.charCode||event.which||event.keyCode,options=this.options,elements=this.elements,visivleElements=elements.getVisibleInstance(),lastElement,ln=visivleElements.length,moveModif,nr;switch(keyCode){case 9:if(!this.options.multiselect){$(this.template.input).trigger('focus',{withoutHandler:true});this.close();break;}
case 40:moveModif=1;case 38:moveModif=moveModif||-1;lastElement=visivleElements.lastActionsElement||visivleElements.elements[0]||{};if(lastElement.container){nr=(visivleElements.getPosition(lastElement.container)+moveModif+ln)%ln;$(lastElement.container).removeClass('hover');lastElement=visivleElements.elements[nr];$(lastElement.container).addClass('hover');elements.lastActionsElement=lastElement;this.scrollToElement(lastElement);}
event.preventDefault();break;case 13:lastElement=visivleElements.lastActionsElement||visivleElements.elements[0]||{};if(lastElement.container&&!options.multiselect){$(lastElement.container).trigger('click',{stopPropagation:true});}
this.close();event.preventDefault();break;case 32:if(search){break;}
lastElement=visivleElements.lastActionsElement||visivleElements.elements[0]||{};if(lastElement.container){$(lastElement.container).trigger('click',{stopPropagation:true});}
if(!options.multiselect){this.close();}
event.preventDefault();break;case 27:this.close();event.preventDefault();break;}},scrollToElement:function(element){var list=this.template.list,scrollTop,offsetTop,offsetHeight,listBound=list.getBoundingClientRect(),listHeight=listBound.height||listBound.bottom-listBound.top;if(element.container){element=element.container;}
offsetTop=element.offsetTop;if(element.nextSibling&&element.nextSibling.offsetTop){offsetHeight=element.nextSibling.offsetTop-element.offsetTop;}else if(element.previousSibling&&element.previousSibling.offsetTop){offsetHeight=element.offsetTop-element.previousSibling.offsetTop;}else{offsetHeight=element.offsetHeight;}
scrollTop=list.scrollTop;if(offsetTop>=scrollTop&&offsetTop+offsetHeight<=scrollTop+listHeight){return;}
if(offsetTop>=scrollTop){if(scrollTop+listHeight+offsetHeight>offsetTop){offsetTop=scrollTop+offsetHeight;}}
scrollTop=Math.max(0,Math.min(list.scrollHeight-listHeight,offsetTop));list.scrollTop=scrollTop;},getTable:function(){var elementsObj=this.elements,selectAllElement=elementsObj.selectAllElement,elementsCopy=elementsObj.elements.slice(),table={total_results:this.elements.length,results:[],selected:[]},i,ln,element;if(this.elements.selectAllElement){table.total_results-=1;}
if(selectAllElement){if(selectAllElement===elementsCopy[0]){elementsCopy.shift();}else if(-1!==elementsCopy.indexOf(selectAllElement)){elementsCopy.splice(elementsCopy.indexOf(selectAllElement),1);}}
for(i=0,ln=elementsCopy.length;i<ln;i+=1){element=elementsCopy[i];element.name=element.label.innerHTML;element.value=element.input.value;element.title=element.container.title;if(element.selected){table.selected.push(element);}}
table.results=elementsCopy;return table;}};style.addRules({'.FullSelectLcContainerDefault.open':'z-index: 10000 !important','.FullSelectLcContainerDefault.open div.FullSelectLcContainerList':'opacity:1; height:auto; display:block','.FullSelectLcContainerDefault.close div.FullSelectLcContainerList':'opacity:0; display:none;','.FullSelectLcContainerDefault div.FullSelectLcContainerList .FullSelectLcSearch.deactivate':'display:none;','.FullSelectLcContainerDefault div.FullSelectLcContainerList ul.list li.searchHide':'display: none;','.FullSelectLcContainerDefault div.FullSelectLcContainerList ul.list input[type="radio"],.FullSelectLcContainerDefault select.fullSelectHide':'opacity:0; position: absolute; left: -9999em;','.FullSelectLcContainerDefault div.FullSelectLcContainerList ul.list':'max-height: 330px; overflow-y: auto;'});return{build:function(select,options,callback){var selectWrapper=create(selectProto);selectWrapper.init(select,options);if('function'===typeof callback){callback(selectWrapper);}}};};$.fn.fullSelectLc=function(options,callback){var that=this;APP.require(APP.files.js.templateBuilder,function(){if('function'===typeof selectBuilder){selectBuilder=selectBuilder();}
that.each(function(){selectBuilder.build(this,options,callback);});});};}(jQuery));